#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

CHANGED_FILES="$(git diff --cached --name-only)"

if echo "$CHANGED_FILES" | grep -qE '^(packages/(core|react)/)'; then
  echo "packages/core or react changed → running knip"
  pnpm knip
fi
